const contributorImageUrl = (perRow: number) =>
    `https://gthanks.aruh1.dev/image?target=aruh1&include_bots=false&per_row=${perRow}&shape=square&limit=1000`

const contributorsImage = contributorImageUrl(20)
const contributorsImageLaptop = contributorImageUrl(16)
const contributorsImageTablet = contributorImageUrl(12)
const contributorsImageMobile = contributorImageUrl(8)

export const thanks = {
    hero: {
        eyebrow: "/thanks",
        titleLines: ["Back the work.", "Fund the next build."],
        description:
            "This page is for the people and teams who keep open-source tools, articles, and late-night shipping sessions alive."
    },
    sponsorNote: {
        text: "If you've donated or helped support my work in any way, feel free to email me and I'll add you to this page.",
        emailLabel: "hi@aruh1.dev",
        href: "mailto:hi@aruh1.dev"
    },
    donationOptions: [
        {
            label: "SPONSORS",
            title: "Send a direct thank you",
            href: "https://aruh1.dev/sponsor",
            action: "Donation",
            description: ""
        },
        {
            label: "Company",
            title: "Sponsor as a team or brand",
            href: "mailto:hi@aruh1.dev",
            action: "Start a conversation",
            description: ""
        }
    ],
    contributors: {
        description: "Thank you to every contributor whose work helps move my projects forward.",
        image: {
            src: contributorsImage,
            laptopSrc: contributorsImageLaptop,
            tabletSrc: contributorsImageTablet,
            mobileSrc: contributorsImageMobile,
            alt: "Aruh1 contributor image generated by GThanks"
        }
    }
} as const

